### ISSUE TITLE
AWS region must be configured either when you configure your CDK stack or through the environment

### ISSUE THREAD

**Issue by denny64** [srhise/nextjs-fargate-cdk#1]
Hi - I went through your tutorial and am getting this error when I do CDK deploy.

`AWS region must be configured either when you configure your CDK stack or through the environment`

The stack properties have been set at the top of the file, but it doesn't look like its being used anywhere?

**Comment by srhise** [comment]
Good question. I realized after this that it doesn't actually use the config code, it is using my AWS_PROFILE from my machine. Will update.

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html

**Comment by srhise** [comment]
This link explains it much better. 

https://docs.aws.amazon.com/cdk/latest/guide/getting_started.html#getting_started_credentials

I know there is also a way to do this in the cdk-stack.js file as well, but the way I had it was not correct.
